apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: service-account-kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  # spec.authorization.acls is required for topic access
  # if simple Kafka spec.kafka.authorization was specified
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: flink.sales.records
        operations:
          - Describe
          - Read
      - resource:
          type: topic
          name: flink.oauth2.auth.sales.records
        operations:
          - Describe
          - Create
          - Write
          - Read
      - resource:
          type: group
          name: sales-record-group
        operations:
          - Read
