apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  labels:
    app: apicurio-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: apicurio/apicurio-registry-mem:latest-release
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-service
spec:
  selector:
    app: apicurio-registry
  ports:
    - protocol: TCP
      port: 8080